---

# Update all the servers, before installing the packages
- hosts: all
  become: true
  tasks:
    - name: Install updates on AlmaLinux
      ansible.builtin.yum:
        name: '*'
        state: latest
        update_cache: yes
      when: ansible_distribution == 'AlmaLinux'

    - name: Install updates on Ubuntu
      ansible.builtin.apt:
        upgrade: dist
        update_cache: yes
      when: ansible_distribution == 'Ubuntu'

# Installing file server on debian
- hosts: file-server-debian
  become: true
  tasks:
    - name: installing file server samba on debian
      tags: file-server, ubuntu, debian,samba
      ansible.builtin.apt:
        name:
          - samba
        state: latest

- hosts: web-server-rpm
  become: true
  tasks:
    - name: Install httpd and PHP
      tags: httpd,php,almalinux,rpm
      ansible.builtin.yum:
        name:
          - httpd
          - php
        state: latest

    - name: Start and enable httpd service
      ansible.builtin.systemd:
        name: httpd
        state: started
        enabled: yes

    - name: Allow HTTP traffic on port 80
      ansible.builtin.firewalld:
        service: http
        permanent: yes
        state: enabled

    - name: Reload firewalld to apply changes
      ansible.builtin.systemd:
        name: firewalld
        state: reloaded


    - name: copy defualt html file into httpd
      tags: apache,httpd,copy
      ansible.builtin.copy:
        src: default_site.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 0644


- hosts: db-server-debian
  become: yes
  tasks:
    - name: Installing maria db server
      tags: db,mariadb,ubuntu,debian
      ansible.builtin.apt:
        name:
          - mariadb-server
        state: latest

- hosts: workstations
  become: true
  tasks:

  - name: install unzip
    ansible.builtin.package:
      name: unzip
  
  - name: install terraform
    ansible.builtin.unarchive:
      src: https://releases.hashicorp.com/terraform/1.8.3/terraform_1.8.3_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root