---

- hosts: all
  become: true
  tasks:
  - name: update reposirory index
    apt:
      update_cache: yes
  - name: remove apache2
    apt:
      name: apache2
      state: present
    apt:
      update_cache: yes