---

########################################################################
################all work that done to all hosts ########################
- hosts: all
  become: true
  pre_tasks:
    - name: Install updates on AlmaLinux
      ansible.builtin.yum:
        name: '*'
        state: latest
        update_cache: yes
      changed_when: false
      when: ansible_distribution == "'AlmaLinux', 'RedHat'"

    - name: Install updates on Ubuntu
      ansible.builtin.apt:
        update_cache: yes
      changed_when: false
      when: ansible_distribution == 'Ubuntu'
  roles:
    - base




##################################################################
################host: file-server Ubuntu  ########################

- hosts: file-server-debian
  become: true
  roles:
    - file_servers



##################################################################
################host: web server AlmaLinux ########################


- hosts: web-server-rpm
  become: true
  roles:
    - web_servers


##################################################################
################host: Maria db on ubuntu  ########################
- hosts: db-server-debian
  become: true
  roles:
    - db_servers

        

##################################################################
################host:   Terraform on RHEL ########################
- hosts: workstations
  become: true
  roles:
    - workstations
