---
- hosts: servers
  become: true
  tasks:
    - name: update repository index
      apt:
        update_cache: yes

    - name: install apache2
      apt:
        name: apache2
        state: present

- hosts: rpm
  become: true
  tasks:
    - name: install httpd
      ansible.builtin.yum:
        name: httpd
        state: present
